# Generated by Django 5.2.9 on 2025-12-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WOUND_CARE', 'Wound Care'), ('BARIATRIC', 'Bariatric')], max_length=20)),
                ('owned_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UtilizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTAL', 'Rental')], max_length=10)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmenttype')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.floor')),
            ],
        ),
        migrations.CreateModel(
            name='FloorSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.floor')),
                ('utilization_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='inventory.utilizationrecord')),
            ],
        ),
    ]
